"""
Spec-Kit bridge adapter for markdown artifact synchronization.

This adapter implements the BridgeAdapter interface to sync Spec-Kit markdown artifacts
(spec.md, plan.md, tasks.md, constitution.md) with SpecFact plan bundles and protocols.
"""

from __future__ import annotations

import hashlib
import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from beartype import beartype
from icontract import ensure, require

from specfact_cli.adapters.base import BridgeAdapter
from specfact_cli.importers.speckit_converter import SpecKitConverter
from specfact_cli.importers.speckit_scanner import SpecKitScanner
from specfact_cli.models.bridge import BridgeConfig
from specfact_cli.models.capabilities import ToolCapabilities
from specfact_cli.models.change import ChangeProposal, ChangeTracking
from specfact_cli.models.project import ProjectBundle
from specfact_cli.utils.icontract_helpers import (
    require_bundle_dir_exists,
    require_file_path_exists,
    require_file_path_is_file,
    require_plan_path_exists,
    require_plan_path_is_file,
    require_repo_path_exists,
    require_repo_path_is_dir,
    require_tasks_path_exists,
    require_tasks_path_is_file,
)


logger = logging.getLogger(__name__)


class SpecKitAdapter(BridgeAdapter):
    """
    Spec-Kit bridge adapter implementing BridgeAdapter interface.

    This adapter provides bidirectional sync between Spec-Kit markdown artifacts
    (generated by Spec-Kit slash commands) and SpecFact plan bundles/protocols.
    """

    @beartype
    @ensure(lambda result: result is None, "Must return None")
    def __init__(self) -> None:
        """Initialize Spec-Kit adapter."""
        self.hash_store: dict[str, str] = {}

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    @ensure(lambda result: isinstance(result, bool), "Must return bool")
    def detect(self, repo_path: Path, bridge_config: BridgeConfig | None = None) -> bool:
        """
        Detect if this is a Spec-Kit repository.

        Args:
            repo_path: Path to repository root
            bridge_config: Optional bridge configuration (for cross-repo detection)

        Returns:
            True if Spec-Kit structure detected, False otherwise
        """
        # Check for cross-repo Spec-Kit
        base_path = repo_path
        if bridge_config and bridge_config.external_base_path:
            base_path = bridge_config.external_base_path

        # Check for Spec-Kit structure
        # Priority: .specify/specs/ (canonical) > docs/specs/ > specs/ (root, legacy)
        specify_dir = base_path / ".specify"
        specify_specs_dir = base_path / ".specify" / "specs"
        specs_dir = base_path / "specs"
        docs_specs_dir = base_path / "docs" / "specs"

        return (
            (specify_specs_dir.exists() and specify_specs_dir.is_dir())
            or (specify_dir.exists() and specify_dir.is_dir())
            or (specs_dir.exists() and specs_dir.is_dir())
            or (docs_specs_dir.exists() and docs_specs_dir.is_dir())
        )

    @beartype
    @ensure(lambda result: result is None or isinstance(result, str), "Must return str or None")
    def _detect_version_from_cli(self, repo_path: Path) -> str | None:
        """Attempt to detect spec-kit version by running the specify CLI."""
        if not shutil.which("specify"):
            return None
        try:
            result = subprocess.run(
                ["specify", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=str(repo_path),
            )
            if result.returncode == 0 and result.stdout.strip():
                version_match = re.search(r"(\d+\.\d+\.\d+)", result.stdout)
                if version_match:
                    return version_match.group(1)
        except subprocess.TimeoutExpired:
            logger.debug("specify --version timed out after 5 seconds")
        except OSError:
            pass
        return None

    @beartype
    @ensure(lambda result: result is None or isinstance(result, str), "Must return str or None")
    def _detect_version_from_heuristics(self, repo_path: Path) -> str | None:
        """Estimate spec-kit version from directory structure presence."""
        if (repo_path / "presets").is_dir():
            return ">=0.3.0"
        if (repo_path / "extensions").is_dir():
            return ">=0.2.0"
        if (repo_path / ".specify").is_dir():
            return ">=0.1.0"
        return None

    @staticmethod
    def _detect_layout(base_path: Path) -> tuple[str, str]:
        """Determine spec-kit layout type and specs directory from repo structure."""
        if (base_path / "docs" / "specs").exists():
            return "modern", "docs/specs"
        if (base_path / ".specify").exists():
            return "modern", "specs"
        return "classic", "specs"

    def _detect_version(self, base_path: Path, *, skip_cli: bool) -> tuple[str | None, str | None]:
        """Detect spec-kit version, returning (version, source)."""
        if not skip_cli:
            version = self._detect_version_from_cli(base_path)
            if version:
                return version, "cli"
        version = self._detect_version_from_heuristics(base_path)
        if version:
            return version, "heuristic"
        return None, None

    @staticmethod
    def _extract_extension_fields(
        ext_list: list[dict[str, Any]],
    ) -> tuple[list[str] | None, dict[str, list[str]] | None]:
        """Extract extension names and command maps from scanner output."""
        if not ext_list:
            return None, None
        names = [e["name"] for e in ext_list]
        commands = {e["name"]: e.get("commands", []) for e in ext_list}
        return names, commands

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    @ensure(lambda result: isinstance(result, ToolCapabilities), "Must return ToolCapabilities")
    def get_capabilities(self, repo_path: Path, bridge_config: BridgeConfig | None = None) -> ToolCapabilities:
        """
        Get Spec-Kit adapter capabilities.

        Args:
            repo_path: Path to repository root
            bridge_config: Optional bridge configuration (for cross-repo detection)

        Returns:
            ToolCapabilities instance for Spec-Kit adapter
        """
        is_cross_repo = bridge_config is not None and bridge_config.external_base_path is not None
        base_path: Path = (
            bridge_config.external_base_path
            if is_cross_repo and bridge_config is not None and bridge_config.external_base_path is not None
            else repo_path
        )

        layout, specs_dir_path = self._detect_layout(base_path)
        scanner = SpecKitScanner(base_path)
        has_constitution, _ = scanner.has_constitution()
        version, detected_version_source = self._detect_version(base_path, skip_cli=is_cross_repo)
        extensions, extension_commands = self._extract_extension_fields(scanner.scan_extensions())
        preset_names = scanner.scan_presets()
        hook_list = scanner.scan_hook_events()

        return ToolCapabilities(
            tool="speckit",
            version=version,
            layout=layout,
            specs_dir=specs_dir_path,
            has_external_config=is_cross_repo,
            has_custom_hooks=has_constitution,
            supported_sync_modes=["bidirectional", "unidirectional"],
            extensions=extensions,
            extension_commands=extension_commands,
            presets=preset_names or None,
            hook_events=hook_list or None,
            detected_version_source=detected_version_source,
        )

    @beartype
    @require(
        lambda artifact_key: isinstance(artifact_key, str) and len(artifact_key) > 0, "Artifact key must be non-empty"
    )
    @ensure(lambda result: result is None, "Must return None")
    def import_artifact(
        self,
        artifact_key: str,
        artifact_path: Path | dict[str, Any],
        project_bundle: Any,  # ProjectBundle - avoid circular import
        bridge_config: BridgeConfig | None = None,
    ) -> None:
        """
        Import artifact from Spec-Kit format to SpecFact.

        Args:
            artifact_key: Artifact key (e.g., "specification", "plan", "tasks")
            artifact_path: Path to artifact file
            project_bundle: Project bundle to update
            bridge_config: Bridge configuration (may contain external_base_path)
        """
        if not isinstance(artifact_path, Path):
            msg = f"Spec-Kit adapter requires Path, got {type(artifact_path)}"
            raise ValueError(msg)

        # Determine base path for cross-repo support
        base_path = artifact_path.parent.parent.parent if bridge_config and bridge_config.external_base_path else None
        if base_path is None:
            base_path = artifact_path.parent.parent.parent  # Navigate from specs/{feature}/spec.md

        scanner = SpecKitScanner(base_path)
        converter = SpecKitConverter(base_path)

        # Parse based on artifact key
        if artifact_key == "specification":
            self._import_specification(artifact_path, project_bundle, scanner, converter, bridge_config)
        elif artifact_key == "plan":
            self._import_plan(artifact_path, project_bundle, scanner, converter, bridge_config)
        elif artifact_key == "tasks":
            self._import_tasks(artifact_path, project_bundle, scanner, converter, bridge_config)
        else:
            msg = f"Unsupported artifact key: {artifact_key}"
            raise ValueError(msg)

    @beartype
    @require(
        lambda artifact_key: isinstance(artifact_key, str) and len(artifact_key) > 0, "Artifact key must be non-empty"
    )
    @ensure(lambda result: isinstance(result, (Path, dict)), "Must return Path or dict")
    def export_artifact(
        self,
        artifact_key: str,
        artifact_data: Any,  # Feature, ChangeProposal, etc. - avoid circular import
        bridge_config: BridgeConfig | None = None,
    ) -> Path | dict[str, Any]:
        """
        Export artifact from SpecFact to Spec-Kit format.

        Args:
            artifact_key: Artifact key (e.g., "specification", "plan", "tasks")
            artifact_data: Data to export (Feature, etc.)
            bridge_config: Bridge configuration (may contain external_base_path)

        Returns:
            Path to exported file
        """
        # Determine base path for cross-repo support
        base_path = None
        if bridge_config and bridge_config.external_base_path:
            base_path = bridge_config.external_base_path
        else:
            # For export, use current directory as base (will be overridden by resolve_path if needed)
            base_path = Path.cwd()

        converter = SpecKitConverter(base_path)

        # Export based on artifact key
        if artifact_key == "specification":
            return self._export_specification(artifact_data, converter, bridge_config)
        if artifact_key == "plan":
            return self._export_plan(artifact_data, converter, bridge_config)
        if artifact_key == "tasks":
            return self._export_tasks(artifact_data, converter, bridge_config)
        msg = f"Unsupported artifact key: {artifact_key}"
        raise ValueError(msg)

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    @ensure(lambda result: isinstance(result, BridgeConfig), "Must return BridgeConfig")
    def generate_bridge_config(self, repo_path: Path) -> BridgeConfig:
        """
        Generate bridge configuration for Spec-Kit.

        Auto-detects format with priority:
        1. .specify/specs/ (canonical - recommended by Spec-Kit)
        2. docs/specs/ (modern layout)
        3. specs/ at root (classic layout - backward compatibility)

        Args:
            repo_path: Path to repository root

        Returns:
            BridgeConfig instance for Spec-Kit
        """
        # Auto-detect format based on actual specs location
        # Priority order: .specify/specs/ > docs/specs/ > specs/ (root)
        # According to Spec-Kit documentation, .specify/specs/ is the canonical location
        specify_specs_dir = repo_path / ".specify" / "specs"
        docs_specs_dir = repo_path / "docs" / "specs"
        classic_specs_dir = repo_path / "specs"

        # Check actual specs location (prioritize .specify/specs/)
        if specify_specs_dir.exists() and specify_specs_dir.is_dir():
            # Canonical format: specs in .specify/specs/ (use modern preset with updated paths)
            return BridgeConfig.preset_speckit_specify()
        if docs_specs_dir.exists() and docs_specs_dir.is_dir():
            # Modern format: specs in docs/specs/
            return BridgeConfig.preset_speckit_modern()
        if classic_specs_dir.exists() and classic_specs_dir.is_dir():
            # Classic format: specs at root (backward compatibility)
            return BridgeConfig.preset_speckit_classic()
        # Default to specify format if .specify exists (most common)
        if (repo_path / ".specify").exists():
            return BridgeConfig.preset_speckit_specify()
        # Otherwise default to classic (will fail later if wrong)
        return BridgeConfig.preset_speckit_classic()

    @beartype
    @require(lambda bundle_dir: isinstance(bundle_dir, Path), "Bundle directory must be Path")
    @require(require_bundle_dir_exists, "Bundle directory must exist")
    @ensure(lambda result: result is None or isinstance(result, ChangeTracking), "Must return ChangeTracking or None")
    def load_change_tracking(
        self, bundle_dir: Path, bridge_config: BridgeConfig | None = None
    ) -> ChangeTracking | None:
        """
        Load change tracking (Spec-Kit doesn't have change tracking).

        Args:
            bundle_dir: Path to bundle directory
            bridge_config: Optional bridge configuration

        Returns:
            None (Spec-Kit doesn't support change tracking)
        """
        return None

    @beartype
    @require(lambda bundle_dir: isinstance(bundle_dir, Path), "Bundle directory must be Path")
    @require(require_bundle_dir_exists, "Bundle directory must exist")
    @require(
        lambda change_tracking: isinstance(change_tracking, ChangeTracking), "Change tracking must be ChangeTracking"
    )
    @ensure(lambda result: result is None, "Must return None")
    def save_change_tracking(
        self, bundle_dir: Path, change_tracking: ChangeTracking, bridge_config: BridgeConfig | None = None
    ) -> None:
        """
        Save change tracking (Spec-Kit doesn't support change tracking).

        Args:
            bundle_dir: Path to bundle directory
            change_tracking: ChangeTracking instance to save
            bridge_config: Optional bridge configuration

        Raises:
            NotImplementedError: Spec-Kit doesn't support change tracking
        """
        msg = "Spec-Kit adapter does not support change tracking"
        raise NotImplementedError(msg)

    @beartype
    @require(lambda bundle_dir: isinstance(bundle_dir, Path), "Bundle directory must be Path")
    @require(require_bundle_dir_exists, "Bundle directory must exist")
    @require(lambda change_name: isinstance(change_name, str) and len(change_name) > 0, "Change name must be non-empty")
    @ensure(lambda result: result is None or isinstance(result, ChangeProposal), "Must return ChangeProposal or None")
    def load_change_proposal(
        self, bundle_dir: Path, change_name: str, bridge_config: BridgeConfig | None = None
    ) -> ChangeProposal | None:
        """
        Load change proposal (Spec-Kit doesn't have change proposals).

        Args:
            bundle_dir: Path to bundle directory
            change_name: Change identifier
            bridge_config: Optional bridge configuration

        Returns:
            None (Spec-Kit doesn't support change proposals)
        """
        return None

    @beartype
    @require(lambda bundle_dir: isinstance(bundle_dir, Path), "Bundle directory must be Path")
    @require(require_bundle_dir_exists, "Bundle directory must exist")
    @require(lambda proposal: isinstance(proposal, ChangeProposal), "Proposal must be ChangeProposal")
    @ensure(lambda result: result is None, "Must return None")
    def save_change_proposal(
        self, bundle_dir: Path, proposal: ChangeProposal, bridge_config: BridgeConfig | None = None
    ) -> None:
        """
        Save change proposal (Spec-Kit doesn't support change proposals).

        Args:
            bundle_dir: Path to bundle directory
            proposal: ChangeProposal instance to save
            bridge_config: Optional bridge configuration

        Raises:
            NotImplementedError: Spec-Kit doesn't support change proposals
        """
        msg = "Spec-Kit adapter does not support change proposals"
        raise NotImplementedError(msg)

    # Private helper methods for import/export

    def _resolve_feature_title(self, spec_data: dict[str, Any], spec_path: Path) -> str:
        """Return the feature title from spec_data, falling back to H1 parsing, then 'Unknown Feature'."""
        feature_title = spec_data.get("feature_title")
        if not feature_title:
            try:
                content = spec_path.read_text(encoding="utf-8")
                title_match = (
                    re.search(r"^#\s+Feature Specification:\s*(.+)$", content, re.MULTILINE)
                    or re.search(r"^#\s+(.+?)\s+Feature", content, re.MULTILINE)
                    or re.search(r"^#\s+(.+)$", content, re.MULTILINE)
                )
                if title_match:
                    feature_title = title_match.group(1).strip()
            except Exception:
                pass
        if not feature_title or feature_title.strip() == "":
            return "Unknown Feature"
        return feature_title

    def _build_stories_from_spec(self, spec_data: dict[str, Any]) -> list[Any]:
        """Convert raw spec story dicts into Story model instances."""
        from specfact_cli.models.plan import Story

        priority_map = {"P1": 8, "P2": 5, "P3": 3, "P4": 1}
        stories: list[Story] = []
        raw_stories = spec_data.get("stories", [])
        if not isinstance(raw_stories, list):
            raw_stories = []
        for story_data in raw_stories:
            if not isinstance(story_data, dict):
                continue
            sd: dict[str, Any] = story_data
            story_key = sd.get("key", "UNKNOWN")
            story_title = sd.get("title", "Unknown Story")
            priority = sd.get("priority", "P3")
            acceptance = sd.get("acceptance", [])
            story_points = priority_map.get(str(priority), 3)
            stories.append(
                Story(
                    key=str(story_key),
                    title=str(story_title),
                    acceptance=acceptance if acceptance else [f"{story_title} is implemented"],
                    tags=[str(priority)],
                    story_points=story_points,
                    value_points=story_points,
                    tasks=[],
                    confidence=0.8,
                    draft=False,
                    scenarios=sd.get("scenarios"),
                    contracts=None,
                )
            )
        return stories

    def _extract_text_list(self, items: list[Any]) -> list[str]:
        """Flatten a list of dicts-with-text or plain strings into a list of strings."""
        result: list[str] = []
        for item in items:
            if isinstance(item, dict):
                it: dict[str, Any] = item
                result.append(str(it.get("text", "")))
            elif isinstance(item, str):
                result.append(item)
        return result

    def _build_speckit_source_tracking(self, spec_path: Path, bridge_config: BridgeConfig | None) -> Any:
        """Build a SourceTracking instance for a Spec-Kit spec file."""
        from specfact_cli.models.source_tracking import SourceTracking

        base_path = spec_path.parent.parent.parent
        speckit_path = str(spec_path.relative_to(base_path))
        source_metadata: dict[str, Any] = {
            "path": speckit_path,
            "speckit_path": speckit_path,
            "speckit_type": "specification",
        }
        if bridge_config and bridge_config.external_base_path:
            source_metadata["speckit_base_path"] = str(bridge_config.external_base_path)
        return SourceTracking(tool="speckit", source_metadata=source_metadata)

    def _upsert_feature(
        self,
        project_bundle: ProjectBundle,
        feature_key: str,
        feature_title: str,
        outcomes: list[str],
        acceptance: list[str],
        stories: list[Any],
        spec_data: dict[str, Any],
        spec_path: Path,
        bridge_config: BridgeConfig | None,
    ) -> None:
        """Insert a new Feature or update the existing one in project_bundle.features."""
        from specfact_cli.models.plan import Feature
        from specfact_cli.utils.feature_keys import normalize_feature_key

        normalized_key = normalize_feature_key(feature_key)
        existing_feature = None
        for key, feat in project_bundle.features.items():
            if normalize_feature_key(key) == normalized_key:
                existing_feature = feat
                break

        if existing_feature:
            existing_feature.title = feature_title
            existing_feature.outcomes = outcomes if outcomes else existing_feature.outcomes
            existing_feature.acceptance = acceptance if acceptance else existing_feature.acceptance
            existing_feature.stories = stories
            existing_feature.constraints = spec_data.get("edge_cases", [])
            return

        feature = Feature(
            key=feature_key,
            title=feature_title,
            outcomes=outcomes if outcomes else [f"Provides {feature_title} functionality"],
            acceptance=acceptance if acceptance else [f"{feature_title} is functional"],
            constraints=spec_data.get("edge_cases", []),
            stories=stories,
            confidence=0.8,
            draft=False,
            source_tracking=None,
            contract=None,
            protocol=None,
        )
        feature.source_tracking = self._build_speckit_source_tracking(spec_path, bridge_config)
        project_bundle.features[feature_key] = feature

    def _import_specification(
        self,
        spec_path: Path,
        project_bundle: ProjectBundle,
        scanner: SpecKitScanner,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,
    ) -> None:
        """Import specification from Spec-Kit spec.md."""
        spec_data = scanner.parse_spec_markdown(spec_path)
        if not spec_data:
            return

        feature_key = spec_data.get("feature_key", spec_path.parent.name.upper().replace("-", "_"))
        feature_title = self._resolve_feature_title(spec_data, spec_path)
        stories = self._build_stories_from_spec(spec_data)
        outcomes = self._extract_text_list(spec_data.get("requirements", []))
        acceptance = self._extract_text_list(spec_data.get("success_criteria", []))

        self._upsert_feature(
            project_bundle,
            feature_key,
            feature_title,
            outcomes,
            acceptance,
            stories,
            spec_data,
            spec_path,
            bridge_config,
        )

    def _read_plan_title(self, plan_path: Path) -> str:
        """Extract title from the first H1 header in plan.md, or return 'Unknown Feature'."""
        try:
            content = plan_path.read_text(encoding="utf-8")
            title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
            return title_match.group(1).strip() if title_match else "Unknown Feature"
        except Exception:
            return "Unknown Feature"

    def _build_plan_source_tracking(self, plan_path: Path, bridge_config: BridgeConfig | None) -> Any:
        """Build SourceTracking for a Spec-Kit plan file."""
        from specfact_cli.models.source_tracking import SourceTracking

        base_path = plan_path.parent.parent.parent
        speckit_path = str(plan_path.relative_to(base_path))
        source_metadata: dict[str, Any] = {
            "path": speckit_path,
            "speckit_path": speckit_path,
            "speckit_type": "plan",
        }
        if bridge_config and bridge_config.external_base_path:
            source_metadata["speckit_base_path"] = str(bridge_config.external_base_path)
        return SourceTracking(tool="speckit", source_metadata=source_metadata)

    @beartype
    @require(require_plan_path_exists, "Plan path must exist")
    @require(require_plan_path_is_file, "Plan path must be a file")
    @require(lambda project_bundle: project_bundle is not None, "Project bundle must not be None")
    @ensure(lambda result: result is None, "Must return None")
    def _import_plan(
        self,
        plan_path: Path,
        project_bundle: ProjectBundle,
        scanner: SpecKitScanner,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,
    ) -> None:
        """Import plan from Spec-Kit plan.md."""
        from specfact_cli.models.plan import Feature
        from specfact_cli.utils.feature_keys import normalize_feature_key

        plan_data = scanner.parse_plan_markdown(plan_path)
        if not plan_data:
            return

        feature_id = plan_path.parent.name
        normalized_feature_id = normalize_feature_key(feature_id)

        matching_feature = None
        for key, feat in project_bundle.features.items():
            if normalize_feature_key(key) == normalized_feature_id:
                matching_feature = feat
                break

        if not matching_feature:
            feature_key = feature_id.upper().replace("-", "_")
            feature_title = self._read_plan_title(plan_path)

            matching_feature = Feature(
                key=feature_key,
                title=feature_title,
                outcomes=[],
                acceptance=[],
                constraints=[],
                stories=[],
                confidence=0.8,
                draft=False,
                source_tracking=None,
                contract=None,
                protocol=None,
            )
            matching_feature.source_tracking = self._build_plan_source_tracking(plan_path, bridge_config)

            project_bundle.features[feature_key] = matching_feature

    @beartype
    @require(require_tasks_path_exists, "Tasks path must exist")
    @require(require_tasks_path_is_file, "Tasks path must be a file")
    @require(lambda project_bundle: project_bundle is not None, "Project bundle must not be None")
    @ensure(lambda result: result is None, "Must return None")
    def _import_tasks(
        self,
        tasks_path: Path,
        project_bundle: ProjectBundle,
        scanner: SpecKitScanner,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,
    ) -> None:
        """Import tasks from Spec-Kit tasks.md."""
        from specfact_cli.utils.feature_keys import normalize_feature_key

        # Parse tasks.md
        tasks_data = scanner.parse_tasks_markdown(tasks_path)
        if not tasks_data:
            return

        # Extract feature ID from path (specs/{feature_id}/tasks.md)
        feature_id = tasks_path.parent.name
        normalized_feature_id = normalize_feature_key(feature_id)

        # Find matching feature in bundle
        matching_feature = None
        for key, feat in project_bundle.features.items():
            if normalize_feature_key(key) == normalized_feature_id:
                matching_feature = feat
                break

        if matching_feature:
            # Map tasks to stories based on story_ref
            raw_tasks = tasks_data.get("tasks", [])
            if not isinstance(raw_tasks, list):
                raw_tasks = []
            for task in raw_tasks:
                if not isinstance(task, dict):
                    continue
                td: dict[str, Any] = task
                story_ref = str(td.get("story_ref", ""))
                task_desc = str(td.get("description", ""))

                # Find matching story
                for story in matching_feature.stories:
                    if story_ref and story_ref in story.key:
                        if not story.tasks:
                            story.tasks = []
                        story.tasks.append(task_desc)
                        break

    @beartype
    @require(lambda feature: feature is not None, "Feature must not be None")
    @ensure(lambda result: isinstance(result, Path), "Must return Path")
    def _export_specification(
        self,
        feature: Any,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,  # Feature
    ) -> Path:
        """Export specification to Spec-Kit spec.md."""
        # Use converter to convert Feature to Spec-Kit spec.md format
        # Implementation details would go here
        msg = "Spec-Kit adapter export_specification not yet fully implemented"
        raise NotImplementedError(msg)

    def _export_plan(
        self,
        plan_data: Any,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,  # PlanBundle or Feature
    ) -> Path:
        """Export plan to Spec-Kit plan.md."""
        from specfact_cli.models.plan import Feature, PlanBundle

        # Determine base path (always Path; external_base_path overrides repo root)
        base_path: Path = Path(converter.repo_path)
        if bridge_config is not None and bridge_config.external_base_path is not None:
            base_path = bridge_config.external_base_path

        # If plan_data is a Feature, we need to get the bundle context
        # For now, we'll generate plan.md for the feature
        if isinstance(plan_data, Feature):
            # Generate plan.md for a single feature (create minimal bundle for context)
            from specfact_cli.models.plan import PlanBundle, Product, Release

            # Create minimal bundle with features as list
            minimal_bundle = PlanBundle(
                version="1.0",
                idea=None,
                business=None,
                product=Product(
                    themes=[], releases=[Release(name="v0.1", objectives=[], scope=[plan_data.key], risks=[])]
                ),
                features=[plan_data],
                metadata=None,
                clarifications=None,
            )
            plan_content = converter._generate_plan_markdown(plan_data, minimal_bundle)
            feature_id = plan_data.key.lower().replace("_", "-")
        elif isinstance(plan_data, PlanBundle):
            # Generate plan.md for first feature (Spec-Kit has one plan.md per feature)
            if plan_data.features:
                feat0: Feature = plan_data.features[0]
                plan_content = converter._generate_plan_markdown(feat0, plan_data)
                feature_id = feat0.key.lower().replace("_", "-")
            else:
                msg = "Plan bundle has no features to export"
                raise ValueError(msg)
        else:
            msg = f"Unsupported plan_data type: {type(plan_data)}"
            raise ValueError(msg)

        # Determine output path from bridge config or use default
        artifact_path: Path
        if bridge_config is not None and "plan" in bridge_config.artifacts:
            artifact_path = bridge_config.resolve_path("plan", {"feature_id": feature_id}, base_path=base_path)
        else:
            artifact_path = base_path / "specs" / feature_id / "plan.md"

        # Ensure directory exists
        artifact_path.parent.mkdir(parents=True, exist_ok=True)

        # Write plan.md
        artifact_path.write_text(plan_content, encoding="utf-8")

        return artifact_path

    @beartype
    @require(lambda feature: feature is not None, "Feature must not be None")
    @ensure(lambda result: isinstance(result, Path), "Must return Path")
    def _export_tasks(
        self,
        feature: Any,
        converter: SpecKitConverter,
        bridge_config: BridgeConfig | None,  # Feature
    ) -> Path:
        """Export tasks to Spec-Kit tasks.md."""
        from specfact_cli.models.plan import Feature

        if not isinstance(feature, Feature):
            msg = f"Expected Feature, got {type(feature)}"
            raise ValueError(msg)

        base_path: Path = Path(converter.repo_path)
        if bridge_config is not None and bridge_config.external_base_path is not None:
            base_path = bridge_config.external_base_path

        # Generate tasks.md content using converter
        tasks_content = converter._generate_tasks_markdown(feature)

        # Determine output path from bridge config or use default
        feature_id = feature.key.lower().replace("_", "-")
        artifact_path: Path
        if bridge_config is not None and "tasks" in bridge_config.artifacts:
            artifact_path = bridge_config.resolve_path("tasks", {"feature_id": feature_id}, base_path=base_path)
        else:
            artifact_path = base_path / "specs" / feature_id / "tasks.md"

        # Ensure directory exists
        artifact_path.parent.mkdir(parents=True, exist_ok=True)

        # Write tasks.md
        artifact_path.write_text(tasks_content, encoding="utf-8")

        return artifact_path

    # Private helper methods for bidirectional sync (from SpecKitSync)

    def _record_md_change(self, repo_path: Path, file_path: Path, changes: dict[str, Any]) -> None:
        relative_path = str(file_path.relative_to(repo_path))
        current_hash = self._get_file_hash(file_path)
        stored_hash = self.hash_store.get(relative_path, "")
        if current_hash == stored_hash:
            return
        changes[relative_path] = {
            "file": file_path,
            "hash": current_hash,
            "type": "modified" if stored_hash else "new",
        }

    def _merge_specs_tree_changes(self, repo_path: Path, specs_root: Path, changes: dict[str, Any]) -> None:
        if not specs_root.exists() or not specs_root.is_dir():
            return
        for spec_dir in specs_root.iterdir():
            if not spec_dir.is_dir():
                continue
            for spec_file in spec_dir.glob("*.md"):
                self._record_md_change(repo_path, spec_file, changes)

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    @ensure(lambda result: isinstance(result, dict), "Must return dict")
    def _detect_speckit_changes(self, repo_path: Path) -> dict[str, Any]:
        """
        Detect changes in Spec-Kit artifacts.

        Args:
            repo_path: Path to repository

        Returns:
            Dictionary of detected changes keyed by file path
        """
        changes: dict[str, Any] = {}
        specify_dir = repo_path / ".specify"
        if specify_dir.exists():
            memory_dir = repo_path / ".specify" / "memory"
            if memory_dir.exists():
                for memory_file in memory_dir.glob("*.md"):
                    self._record_md_change(repo_path, memory_file, changes)

        specify_specs_dir = repo_path / ".specify" / "specs"
        docs_specs_dir = repo_path / "docs" / "specs"
        classic_specs_dir = repo_path / "specs"

        if specify_specs_dir.exists() and specify_specs_dir.is_dir():
            self._merge_specs_tree_changes(repo_path, specify_specs_dir, changes)
        elif docs_specs_dir.exists() and docs_specs_dir.is_dir():
            self._merge_specs_tree_changes(repo_path, docs_specs_dir, changes)
        elif classic_specs_dir.exists() and classic_specs_dir.is_dir():
            self._merge_specs_tree_changes(repo_path, classic_specs_dir, changes)

        return changes

    def _detect_specfact_changes(self, repo_path: Path) -> dict[str, Any]:
        """
        Detect changes in SpecFact artifacts.

        Args:
            repo_path: Path to repository

        Returns:
            Dictionary of detected changes keyed by file path
        """
        changes: dict[str, Any] = {}

        # Monitor .specfact/plans/ files
        plans_dir = repo_path / ".specfact" / "plans"
        if plans_dir.exists():
            for plan_file in plans_dir.glob("*.yaml"):
                relative_path = str(plan_file.relative_to(repo_path))
                current_hash = self._get_file_hash(plan_file)
                stored_hash = self.hash_store.get(relative_path, "")

                if current_hash != stored_hash:
                    changes[relative_path] = {
                        "file": plan_file,
                        "hash": current_hash,
                        "type": "modified" if stored_hash else "new",
                    }

        # Monitor .specfact/protocols/ files
        protocols_dir = repo_path / ".specfact" / "protocols"
        if protocols_dir.exists():
            for protocol_file in protocols_dir.glob("*.yaml"):
                relative_path = str(protocol_file.relative_to(repo_path))
                current_hash = self._get_file_hash(protocol_file)
                stored_hash = self.hash_store.get(relative_path, "")

                if current_hash != stored_hash:
                    changes[relative_path] = {
                        "file": protocol_file,
                        "hash": current_hash,
                        "type": "modified" if stored_hash else "new",
                    }

        return changes

    @beartype
    @require(lambda speckit_changes: isinstance(speckit_changes, dict), "Speckit changes must be dict")
    @require(lambda specfact_changes: isinstance(specfact_changes, dict), "Specfact changes must be dict")
    @ensure(lambda result: isinstance(result, dict), "Must return dict")
    def _merge_changes(self, speckit_changes: dict[str, Any], specfact_changes: dict[str, Any]) -> dict[str, Any]:
        """
        Merge changes from both sources.

        Args:
            speckit_changes: Spec-Kit detected changes
            specfact_changes: SpecFact detected changes

        Returns:
            Merged changes dictionary
        """
        merged: dict[str, Any] = {}

        # Merge Spec-Kit changes
        for key, change in speckit_changes.items():
            merged[key] = {
                "source": "speckit",
                **change,
            }

        # Merge SpecFact changes
        for key, change in specfact_changes.items():
            if key in merged:
                # Conflict detected
                merged[key]["conflict"] = True
                merged[key]["specfact_change"] = change
            else:
                merged[key] = {
                    "source": "specfact",
                    **change,
                }

        return merged

    @beartype
    @require(lambda speckit_changes: isinstance(speckit_changes, dict), "Speckit changes must be dict")
    @require(lambda specfact_changes: isinstance(specfact_changes, dict), "Specfact changes must be dict")
    @ensure(lambda result: isinstance(result, list), "Must return list")
    def _detect_conflicts(
        self, speckit_changes: dict[str, Any], specfact_changes: dict[str, Any]
    ) -> list[dict[str, Any]]:
        """
        Detect conflicts between Spec-Kit and SpecFact changes.

        Args:
            speckit_changes: Spec-Kit detected changes
            specfact_changes: SpecFact detected changes

        Returns:
            List of conflict dictionaries
        """
        conflicts: list[dict[str, Any]] = []

        for key in set(speckit_changes.keys()) & set(specfact_changes.keys()):
            conflicts.append(
                {
                    "key": key,
                    "speckit_change": speckit_changes[key],
                    "specfact_change": specfact_changes[key],
                }
            )

        return conflicts

    def _resolve_conflicts(self, conflicts: list[dict[str, Any]]) -> dict[str, Any]:
        """
        Resolve conflicts with merge strategy.

        Strategy:
        - Priority: SpecFact > Spec-Kit for artifacts (specs/*)
        - Priority: Spec-Kit > SpecFact for memory files (.specify/memory/)

        Args:
            conflicts: List of conflict dictionaries

        Returns:
            Dictionary of resolved conflicts
        """
        resolved: dict[str, Any] = {}

        for conflict in conflicts:
            key = conflict["key"]
            if key.startswith(".specify/memory/"):
                # Memory files: Spec-Kit wins
                resolved[key] = "speckit"
            else:
                # Artifacts: SpecFact wins
                resolved[key] = "specfact"

        return resolved

    @beartype
    @require(require_file_path_exists, "File path must exist")
    @require(require_file_path_is_file, "File path must be a file")
    @ensure(lambda result: isinstance(result, str) and len(result) == 64, "Must return 64-char hex digest")
    def _get_file_hash(self, file_path: Path) -> str:
        """
        Get SHA256 hash of file content.

        Args:
            file_path: Path to file

        Returns:
            Hex digest of file hash
        """
        content = file_path.read_bytes()
        return hashlib.sha256(content).hexdigest()

    # Public helper methods for sync operations (used by sync.py)

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    def discover_features(self, repo_path: Path, bridge_config: BridgeConfig | None = None) -> list[dict[str, Any]]:
        """
        Discover features from Spec-Kit repository.

        This is a public helper method for sync operations to discover features
        without directly instantiating SpecKitScanner.

        Args:
            repo_path: Path to repository root
            bridge_config: Optional bridge configuration (for cross-repo support)

        Returns:
            List of feature dictionaries
        """
        base_path = repo_path
        if bridge_config and bridge_config.external_base_path:
            base_path = bridge_config.external_base_path

        scanner = SpecKitScanner(base_path)
        return scanner.discover_features()

    @beartype
    @require(require_repo_path_exists, "Repository path must exist")
    @require(require_repo_path_is_dir, "Repository path must be a directory")
    @require(
        lambda direction: direction in ("speckit", "specfact", "both"),
        "Direction must be 'speckit', 'specfact', or 'both'",
    )
    @ensure(lambda result: isinstance(result, dict), "Must return dict")
    def detect_changes(
        self, repo_path: Path, direction: str = "both", bridge_config: BridgeConfig | None = None
    ) -> dict[str, Any]:
        """
        Detect changes in Spec-Kit or SpecFact artifacts.

        This is a public helper method for sync operations to detect changes
        without directly instantiating SpecKitSync.

        Args:
            repo_path: Path to repository root
            direction: Direction to detect changes ("speckit", "specfact", or "both")
            bridge_config: Optional bridge configuration (for cross-repo support)

        Returns:
            Dictionary with "speckit_changes" and/or "specfact_changes" keys
        """
        base_path = repo_path
        if bridge_config and bridge_config.external_base_path:
            base_path = bridge_config.external_base_path

        result: dict[str, Any] = {}
        if direction in ("speckit", "both"):
            result["speckit_changes"] = self._detect_speckit_changes(base_path)
        if direction in ("specfact", "both"):
            result["specfact_changes"] = self._detect_specfact_changes(base_path)
        return result

    @beartype
    @require(lambda speckit_changes: isinstance(speckit_changes, dict), "Speckit changes must be dict")
    @require(lambda specfact_changes: isinstance(specfact_changes, dict), "Specfact changes must be dict")
    @ensure(lambda result: isinstance(result, list), "Must return list")
    def detect_conflicts(
        self, speckit_changes: dict[str, Any], specfact_changes: dict[str, Any]
    ) -> list[dict[str, Any]]:
        """
        Detect conflicts between Spec-Kit and SpecFact changes.

        This is a public helper method for sync operations to detect conflicts.

        Args:
            speckit_changes: Spec-Kit detected changes
            specfact_changes: SpecFact detected changes

        Returns:
            List of conflict dictionaries
        """
        return self._detect_conflicts(speckit_changes, specfact_changes)

    @beartype
    @require(lambda plan_bundle: plan_bundle is not None, "Plan bundle must not be None")
    def export_bundle(
        self,
        plan_bundle: Any,  # PlanBundle - avoid circular import
        repo_path: Path,
        progress_callback: Any | None = None,  # Callable[[int, int], None] - avoid circular import
        bridge_config: BridgeConfig | None = None,
    ) -> int:
        """
        Export a full plan bundle to Spec-Kit format.

        This is a public helper method for sync operations to export entire bundles.
        It's a convenience method that wraps the bundle-level conversion operation.

        Args:
            plan_bundle: PlanBundle to export
            repo_path: Path to repository root
            progress_callback: Optional callback function(current: int, total: int) for progress updates
            bridge_config: Optional bridge configuration (for cross-repo support)

        Returns:
            Number of features converted
        """
        base_path = repo_path
        if bridge_config and bridge_config.external_base_path:
            base_path = bridge_config.external_base_path

        converter = SpecKitConverter(base_path)
        return converter.convert_to_speckit(plan_bundle, progress_callback)
