"""
Enrichment parser for LLM-generated enrichment reports.

This module parses Markdown enrichment reports generated by LLMs during
the dual-stack enrichment workflow and applies them to plan bundles.
"""

from __future__ import annotations

import re
from contextlib import suppress
from pathlib import Path
from typing import Any, cast

from beartype import beartype
from icontract import ensure, require

from specfact_cli.models.plan import Feature, PlanBundle, Story


_NO_REGEX_FLAGS = 0


def _contains_disallowed_control_chars(text: str) -> bool:
    """Return whether text contains control characters beyond normal whitespace."""

    return any(ord(char) < 32 and char not in "\n\r\t" for char in text)


def _safe_search(pattern: str, text: str, flags: int = _NO_REGEX_FLAGS) -> re.Match[str] | None:
    """Return a regex search result, or None when regex evaluation fails."""

    try:
        return re.search(pattern, text, flags)
    except re.error:
        return None


def _safe_findall(pattern: str, text: str, flags: int = _NO_REGEX_FLAGS) -> list[str] | list[tuple[str, ...]]:
    """Return regex matches, or an empty list when regex evaluation fails."""

    try:
        return re.findall(pattern, text, flags)
    except re.error:
        return []


def _story_from_dict_with_key(story_data: dict[str, Any], key: str) -> Story:
    return Story(
        key=key,
        title=story_data.get("title", "Untitled Story"),
        acceptance=story_data.get("acceptance", []),
        story_points=story_data.get("story_points"),
        value_points=story_data.get("value_points"),
        tasks=story_data.get("tasks", []),
        confidence=story_data.get("confidence", 0.8),
        draft=False,
        scenarios=None,
        contracts=None,
    )


def _merge_missing_stories_into_feature(
    existing_feature: Feature, stories_data: list[Any], existing_story_keys: set[str]
) -> None:
    for story_data in stories_data:
        if not isinstance(story_data, dict):
            continue
        story_d: dict[str, Any] = cast(dict[str, Any], story_data)
        story_key = story_d.get("key", "")
        if not story_key or story_key in existing_story_keys:
            continue
        existing_feature.stories.append(_story_from_dict_with_key(story_data, story_key))
        existing_story_keys.add(story_key)


def _merge_missing_into_existing_feature(
    existing_feature: Feature,
    missing_feature_data: dict[str, Any],
) -> None:
    if "confidence" in missing_feature_data:
        existing_feature.confidence = missing_feature_data["confidence"]
    if "title" in missing_feature_data and missing_feature_data["title"] and not existing_feature.title:
        existing_feature.title = missing_feature_data["title"]
    if "outcomes" in missing_feature_data:
        for outcome in missing_feature_data["outcomes"]:
            if outcome not in existing_feature.outcomes:
                existing_feature.outcomes.append(outcome)
    stories_data = missing_feature_data.get("stories", [])
    if not stories_data:
        return
    existing_story_keys = {s.key for s in existing_feature.stories}
    _merge_missing_stories_into_feature(existing_feature, stories_data, existing_story_keys)


def _append_new_feature_from_missing(enriched: PlanBundle, missing_feature_data: dict[str, Any]) -> None:
    stories_data = missing_feature_data.get("stories", [])
    stories: list[Story] = []
    for story_data in stories_data:
        if isinstance(story_data, dict):
            sd: dict[str, Any] = cast(dict[str, Any], story_data)
            stories.append(
                _story_from_dict_with_key(
                    sd,
                    sd.get("key", f"STORY-{len(stories) + 1:03d}"),
                )
            )
    feature = Feature(
        key=missing_feature_data.get("key", f"FEATURE-{len(enriched.features) + 1:03d}"),
        title=missing_feature_data.get("title", "Untitled Feature"),
        outcomes=missing_feature_data.get("outcomes", []),
        acceptance=[],
        constraints=[],
        stories=stories,
        confidence=missing_feature_data.get("confidence", 0.5),
        draft=False,
        source_tracking=None,
        contract=None,
        protocol=None,
    )
    enriched.features.append(feature)


class EnrichmentReport:
    """Parsed enrichment report from LLM."""

    def __init__(self) -> None:
        """Initialize empty enrichment report."""
        self.missing_features: list[dict[str, Any]] = []
        self.confidence_adjustments: dict[str, float] = {}
        self.business_context: dict[str, list[str]] = {
            "priorities": [],
            "constraints": [],
            "unknowns": [],
        }

    @beartype
    @require(lambda feature: isinstance(feature, dict), "Feature must be dictionary")
    def add_missing_feature(self, feature: dict[str, Any]) -> None:
        """Add a missing feature discovered by LLM."""
        self.missing_features.append(feature)

    @beartype
    @require(lambda feature_key: isinstance(feature_key, str), "Feature key must be string")
    @require(lambda confidence: 0.0 <= confidence <= 1.0, "Confidence must be 0.0-1.0")
    def adjust_confidence(self, feature_key: str, confidence: float) -> None:
        """Adjust confidence score for a feature."""
        self.confidence_adjustments[feature_key] = confidence

    @beartype
    @require(lambda category: isinstance(category, str), "Category must be string")
    @require(lambda items: isinstance(items, list), "Items must be list")
    def add_business_context(self, category: str, items: list[str]) -> None:
        """Add business context items."""
        if category in self.business_context:
            self.business_context[category].extend(items)


def _extract_feature_title(feature_text: str) -> str:
    """Extract title from bold text or number-prefixed bold text."""
    title_match = _safe_search(r"^\*\*([^*]+)\*\*", feature_text, re.MULTILINE)
    if not title_match:
        title_match = _safe_search(r"^\d+\.\s*\*\*([^*]+)\*\*", feature_text, re.MULTILINE)
    return title_match.group(1).strip() if title_match else ""


def _extract_feature_key(feature_text: str, title: str) -> str:
    """Extract or generate a feature key from the text."""
    key_match = _safe_search(r"\(Key:\s*([A-Z0-9_-]+)\)", feature_text, re.IGNORECASE)
    if not key_match:
        key_match = _safe_search(r"(?:key|Key):\s*([A-Z0-9_-]+)", feature_text, re.IGNORECASE)
    if key_match:
        return key_match.group(1)
    if title:
        return f"FEATURE-{title.upper().replace(' ', '').replace('-', '')[:20]}"
    return ""


def _extract_feature_outcomes(feature_text: str) -> list[str]:
    """Extract outcomes and business reason/value from feature text."""
    outcomes: list[str] = []
    outcomes_match = _safe_search(
        r"(?:outcomes?|Outcomes?):\s*(.+?)(?:\n\s*(?:stories?|Stories?):|\Z)",
        feature_text,
        re.IGNORECASE | re.DOTALL,
    )
    if outcomes_match:
        outcomes_text = outcomes_match.group(1).strip()
        outcomes = [
            o.strip() for o in re.split(r"\n|,", outcomes_text) if o.strip() and not o.strip().startswith("- Stories:")
        ]

    reason_match = _safe_search(
        r"(?:reason|Reason|Business value):\s*(.+?)(?:\n(?:stories?|Stories?)|$)",
        feature_text,
        re.IGNORECASE | re.DOTALL,
    )
    if reason_match:
        reason = reason_match.group(1).strip()
        if reason and reason not in outcomes:
            outcomes.append(reason)
    return outcomes


def _extract_story_title(story_text: str) -> str:
    """Extract story title from bold text, a title field, or the first line."""
    title_match = _safe_search(r"^\*\*([^*]+)\*\*", story_text, re.MULTILINE)
    if title_match:
        return title_match.group(1).strip()

    title_kw = _safe_search(r"(?:title|Title):\s*(.+?)(?:\n|$)", story_text, re.IGNORECASE)
    if title_kw:
        return title_kw.group(1).strip()

    first_line = next((line.strip() for line in story_text.splitlines() if line.strip()), "")
    return re.sub(r"^\d+\.\s*", "", first_line).strip()


def _acceptance_items_from_field_text(acceptance_text: str) -> list[str]:
    items: list[str] = []
    for segment in re.split(r"\n|;", acceptance_text):
        for piece in re.split(r",\s*", segment):
            p = piece.strip(" -*")
            if p:
                items.append(p)
    return items


def _bullet_acceptance_lines(story_text: str, title: str) -> list[str]:
    bullet_acceptance = [
        line.strip(" -*")
        for line in story_text.splitlines()
        if line.strip().startswith(("-", "*")) and len(line.strip()) > 1
    ]
    return [item for item in bullet_acceptance if item and item != title]


def _extract_story_acceptance(story_text: str, title: str) -> list[str]:
    """Extract acceptance criteria from a story block."""
    acceptance_match = _safe_search(
        r"(?:acceptance(?:\s+criteria)?|criteria):\s*(.+?)(?:\n(?:tasks?|Tasks?|story\s+points?|Story\s+points?)|$)",
        story_text,
        re.IGNORECASE | re.DOTALL,
    )
    acceptance: list[str] = []
    if acceptance_match:
        acceptance_text = acceptance_match.group(1).strip()
        acceptance = _acceptance_items_from_field_text(acceptance_text)

    if not acceptance and title:
        acceptance = _bullet_acceptance_lines(story_text, title)

    return acceptance


def _extract_story_points(story_text: str) -> tuple[float | int | None, float | int | None]:
    """Extract story points and value points from a story block."""
    points_match = _safe_search(
        r"(?:story\s+points?|points?)\s*[:=]\s*([0-9]+(?:\.[0-9]+)?)",
        story_text,
        re.IGNORECASE,
    )
    value_points_match = _safe_search(
        r"(?:value\s+points?|value)\s*[:=]\s*([0-9]+(?:\.[0-9]+)?)",
        story_text,
        re.IGNORECASE,
    )

    def _parse_number(match: re.Match[str] | None) -> float | int | None:
        if not match:
            return None
        value = match.group(1)
        if "." in value:
            return float(value)
        return int(value)

    return _parse_number(points_match), _parse_number(value_points_match)


class EnrichmentParser:
    """Parser for Markdown enrichment reports."""

    @beartype
    @require(
        lambda report_path: isinstance(report_path, (Path, str)) and bool(str(report_path).strip()),
        "Report path must be non-empty Path or str",
    )
    @ensure(lambda result: isinstance(result, EnrichmentReport), "Must return EnrichmentReport")
    def parse(self, report_path: Path | str) -> EnrichmentReport:
        """
        Parse Markdown enrichment report.

        Args:
            report_path: Path to Markdown enrichment report (must be non-empty)

        Returns:
            Parsed EnrichmentReport

        Raises:
            FileNotFoundError: If report file doesn't exist
            ValueError: If report_path is empty or invalid
        """
        report_path_str = str(report_path)
        if not report_path_str.strip():
            raise ValueError("Report path cannot be empty")
        if _contains_disallowed_control_chars(report_path_str):
            return EnrichmentReport()

        report_path = Path(report_path_str)
        if not report_path.exists():
            raise FileNotFoundError(f"Enrichment report not found: {report_path}")
        if report_path.is_dir():
            raise ValueError(f"Report path must be a file, not a directory: {report_path}")

        content = report_path.read_text(encoding="utf-8")
        report = EnrichmentReport()

        # Parse missing features section
        self._parse_missing_features(content, report)

        # Parse confidence adjustments section
        self._parse_confidence_adjustments(content, report)

        # Parse business context section
        self._parse_business_context(content, report)

        return report

    @beartype
    @require(lambda content: isinstance(content, str), "Content must be string")
    @require(lambda report: isinstance(report, EnrichmentReport), "Report must be EnrichmentReport")
    def _parse_missing_features(self, content: str, report: EnrichmentReport) -> None:
        """Parse missing features section from enrichment report."""
        if _contains_disallowed_control_chars(content):
            return
        # Look for "Missing Features" or "Missing features" section
        pattern = r"##\s*(?:Missing\s+)?Features?\s*(?:\(.*?\))?\s*\n(.*?)(?=##|\Z)"
        match = _safe_search(pattern, content, re.IGNORECASE | re.DOTALL)
        if not match:
            return

        section = match.group(1)

        # Extract individual features (numbered or bulleted)
        # Stop at next feature (numbered item at start of line, optionally followed by bold text)
        # This avoids stopping at story numbers which are indented
        feature_pattern = r"(?:^|\n)(?:\d+\.|\*|\-)\s*(.+?)(?=\n(?:^\d+\.\s*\*\*|^\d+\.\s+[A-Z]|\*|\-|\Z))"
        features = _safe_findall(feature_pattern, section, re.MULTILINE | re.DOTALL)

        for feature_text in features:
            if not isinstance(feature_text, str):
                continue
            feature = self._parse_feature_block(feature_text)
            if feature:
                report.add_missing_feature(feature)

    @beartype
    @require(lambda feature_text: isinstance(feature_text, str), "Feature text must be string")
    @ensure(lambda result: result is None or isinstance(result, dict), "Must return None or dict")
    def _parse_feature_block(self, feature_text: str) -> dict[str, Any] | None:
        """Parse a single feature block from enrichment report."""
        if _contains_disallowed_control_chars(feature_text):
            return None
        feature: dict[str, Any] = {
            "key": "",
            "title": "",
            "confidence": 0.5,
            "outcomes": [],
            "stories": [],
        }

        feature["title"] = _extract_feature_title(feature_text)
        feature["key"] = _extract_feature_key(feature_text, feature["title"])
        if not feature["title"]:
            title_kw = _safe_search(r"(?:title|Title):\s*(.+?)(?:\n|$)", feature_text, re.IGNORECASE)
            if title_kw:
                feature["title"] = title_kw.group(1).strip()

        confidence_match = _safe_search(r"(?:confidence|Confidence):\s*([0-9.]+)", feature_text, re.IGNORECASE)
        if confidence_match:
            with suppress(ValueError):
                feature["confidence"] = float(confidence_match.group(1))

        feature["outcomes"] = _extract_feature_outcomes(feature_text)

        stories_match = _safe_search(
            r"(?:stories?|Stories?):\s*(.+?)(?=\n\d+\.\s*\*\*|\n##|\Z)", feature_text, re.IGNORECASE | re.DOTALL
        )
        if stories_match:
            stories_text = stories_match.group(1).strip()
            feature["stories"] = self._parse_stories_from_text(stories_text, feature.get("key", ""))

        if feature["key"] or feature["title"]:
            return feature
        return None

    @beartype
    @require(lambda stories_text: isinstance(stories_text, str), "Stories text must be string")
    @require(lambda feature_key: isinstance(feature_key, str), "Feature key must be string")
    @ensure(lambda result: isinstance(result, list), "Must return list of story dicts")
    def _parse_stories_from_text(self, stories_text: str, feature_key: str) -> list[dict[str, Any]]:
        """Parse stories from enrichment report text."""
        if _contains_disallowed_control_chars(stories_text):
            return []
        stories: list[dict[str, Any]] = []

        # Extract individual stories (numbered, bulleted, or sub-headers)
        # Pattern matches: "1. Story title", "- Story title", "### Story title", etc.
        # Handle indented stories (common in nested lists)
        # Match numbered stories with optional indentation: "    1. Story title" or "1. Story title"
        story_pattern = r"(?:^|\n)(?:\s*)(?:\d+\.)\s*(.+?)(?=\n(?:\s*)(?:\d+\.)|\Z)"
        story_matches = _safe_findall(story_pattern, stories_text, re.MULTILINE | re.DOTALL)

        # If no matches with numbered pattern, try bulleted pattern
        if not story_matches:
            story_pattern = r"(?:^|\n)(?:\s*)(?:\*|\-)\s*(.+?)(?=\n(?:\s*)(?:\*|\-|\d+\.)|\Z)"
            story_matches = _safe_findall(story_pattern, stories_text, re.MULTILINE | re.DOTALL)

        for idx, story_text in enumerate(story_matches, start=1):
            if not isinstance(story_text, str):
                continue
            story = self._parse_story_block(story_text, feature_key, idx)
            if story:
                stories.append(story)

        return stories

    @beartype
    @require(lambda story_text: isinstance(story_text, str), "Story text must be string")
    @require(lambda feature_key: isinstance(feature_key, str), "Feature key must be string")
    @require(
        lambda story_number: isinstance(story_number, int) and story_number > 0, "Story number must be positive int"
    )
    @ensure(lambda result: result is None or isinstance(result, dict), "Must return None or story dict")
    def _parse_story_block(self, story_text: str, feature_key: str, story_number: int) -> dict[str, Any] | None:
        """Parse a single story block from enrichment report."""
        if _contains_disallowed_control_chars(story_text):
            return None
        story: dict[str, Any] = {
            "key": "",
            "title": "",
            "acceptance": [],
            "story_points": None,
            "value_points": None,
            "tasks": [],
            "confidence": 0.8,
        }

        if feature_key:
            base = feature_key.replace("FEATURE-", "").upper()
            story["key"] = f"STORY-{base}-{story_number:03d}"
        else:
            story["key"] = f"STORY-{story_number:03d}"

        story["title"] = _extract_story_title(story_text)
        story["acceptance"] = _extract_story_acceptance(story_text, story.get("title", ""))

        tasks_match = _safe_search(
            r"(?:tasks?|Tasks?):\s*(.+?)(?:\n(?:points?|Points?|$))", story_text, re.IGNORECASE | re.DOTALL
        )
        if tasks_match:
            story["tasks"] = [t.strip() for t in re.split(r"\n|,", tasks_match.group(1)) if t.strip()]

        story["story_points"], story["value_points"] = _extract_story_points(story_text)

        if story["title"]:
            return story
        return None

    @beartype
    @require(lambda content: isinstance(content, str), "Content must be string")
    @require(lambda report: isinstance(report, EnrichmentReport), "Report must be EnrichmentReport")
    def _parse_confidence_adjustments(self, content: str, report: EnrichmentReport) -> None:
        """Parse confidence adjustments section from enrichment report."""
        if _contains_disallowed_control_chars(content):
            return
        # Look for "Confidence Adjustments" or "Confidence adjustments" section
        pattern = r"##\s*Confidence\s+Adjustments?\s*\n(.*?)(?=##|\Z)"
        match = _safe_search(pattern, content, re.IGNORECASE | re.DOTALL)
        if not match:
            return

        section = match.group(1)

        # Extract adjustments (format: "FEATURE-KEY → 0.95" or "FEATURE-KEY: 0.95")
        adjustment_pattern = r"([A-Z0-9_-]+)\s*(?:→|:)\s*([0-9.]+)"
        adjustments = _safe_findall(adjustment_pattern, section, re.IGNORECASE)

        for feature_key, confidence_str in adjustments:
            try:
                confidence = float(confidence_str)
                if 0.0 <= confidence <= 1.0:
                    report.adjust_confidence(feature_key.upper(), confidence)
            except ValueError:
                pass

    @beartype
    @require(lambda content: isinstance(content, str), "Content must be string")
    @require(lambda report: isinstance(report, EnrichmentReport), "Report must be EnrichmentReport")
    def _parse_business_context(self, content: str, report: EnrichmentReport) -> None:
        """Parse business context section from enrichment report."""
        if _contains_disallowed_control_chars(content):
            return
        pattern = r"##\s*Business\s+Context\s*\n(.*?)(?=##|\Z)"
        match = _safe_search(pattern, content, re.IGNORECASE | re.DOTALL)
        if not match:
            return

        section = match.group(1)

        def _add_list_from_heading(regex: str, category: str) -> None:
            m = _safe_search(regex, section, re.IGNORECASE | re.DOTALL)
            if not m:
                return
            text = m.group(1)
            items = [x.strip() for x in re.split(r"\n|,", text) if x.strip() and not x.strip().startswith("-")]
            report.add_business_context(category, items)

        _add_list_from_heading(r"(?:Priorities?|Priority):\s*(.+?)(?:\n(?:Constraints?|Unknowns?)|$)", "priorities")
        _add_list_from_heading(r"(?:Constraints?|Constraint):\s*(.+?)(?:\n(?:Unknowns?|Priorities?)|$)", "constraints")
        _add_list_from_heading(r"(?:Unknowns?|Unknown):\s*(.+?)(?:\n(?:Priorities?|Constraints?)|$)", "unknowns")


@beartype
@require(lambda plan_bundle: isinstance(plan_bundle, PlanBundle), "Plan bundle must be PlanBundle")
@require(lambda enrichment: isinstance(enrichment, EnrichmentReport), "Enrichment must be EnrichmentReport")
@ensure(lambda result: isinstance(result, PlanBundle), "Must return PlanBundle")
def apply_enrichment(plan_bundle: PlanBundle, enrichment: EnrichmentReport) -> PlanBundle:
    """
    Apply enrichment report to plan bundle.

    Args:
        plan_bundle: Original plan bundle from CLI
        enrichment: Parsed enrichment report

    Returns:
        Enriched plan bundle
    """
    # Create a copy to avoid mutating the original
    enriched = plan_bundle.model_copy(deep=True)

    # Apply confidence adjustments
    feature_keys = {f.key: i for i, f in enumerate(enriched.features)}
    for feature_key, new_confidence in enrichment.confidence_adjustments.items():
        if feature_key in feature_keys:
            enriched.features[feature_keys[feature_key]].confidence = new_confidence

    # Add missing features
    for missing_feature_data in enrichment.missing_features:
        feature_key = missing_feature_data.get("key", "")
        if feature_key and feature_key in feature_keys:
            existing_idx = feature_keys[feature_key]
            _merge_missing_into_existing_feature(enriched.features[existing_idx], missing_feature_data)
        else:
            _append_new_feature_from_missing(enriched, missing_feature_data)

    # Apply business context to idea if present
    if enriched.idea and enrichment.business_context and enrichment.business_context.get("constraints"):
        if enriched.idea.constraints is None:
            enriched.idea.constraints = []
        enriched.idea.constraints.extend(enrichment.business_context["constraints"])

    return enriched
