#!/usr/bin/env python3
"""Refresh the committed frozen dependency inputs after reviewed metadata changes."""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from beartype import beartype
from icontract import ensure


REPO_ROOT = Path(__file__).resolve().parents[1]
LOCKED_EXPORT = REPO_ROOT / "requirements" / "ci" / "locked.txt"
CODE_REVIEW_REQUIREMENTS_INPUT = REPO_ROOT / "requirements" / "code-review" / "requirements.in"
CODE_REVIEW_LOCKED_EXPORT = REPO_ROOT / "requirements" / "code-review" / "locked.txt"
UV_COMMAND_TIMEOUT_SECONDS = 120


@beartype
def _is_newline_terminated(result: str) -> bool:
    """Return whether rendered lock content ends in a newline."""
    return result.endswith("\n")


@beartype
@ensure(lambda result: result is None, "must return None")  # pyright: ignore[reportUnknownArgumentType, reportUnknownLambdaType]
def validate_locked_export_path(output_path: Path, repository_root: Path = REPO_ROOT) -> None:
    """Reject output paths that would traverse a repository-controlled symlink."""
    try:
        relative_path = output_path.relative_to(repository_root)
    except ValueError as error:
        raise OSError(f"locked export path escapes the repository: {output_path}") from error

    parent = repository_root
    for part in relative_path.parts[:-1]:
        parent = parent / part
        if parent.is_symlink():
            raise OSError(f"locked export parent must not be a symlink: {parent}")
        if parent.exists():
            if not parent.is_dir():
                raise OSError(f"locked export parent is not a directory: {parent}")
            continue
        parent.mkdir()
    if output_path.is_symlink():
        raise OSError(f"locked export path must not be a symlink: {output_path}")
    if output_path.exists() and not output_path.is_file():
        raise OSError(f"locked export path is not a regular file: {output_path}")


@beartype
@ensure(lambda result: result is None, "must return None")  # pyright: ignore[reportUnknownArgumentType, reportUnknownLambdaType]
def run(command: list[str]) -> None:
    """Run one checked-in refresh command from the repository root."""
    subprocess.run(command, cwd=REPO_ROOT, check=True, timeout=UV_COMMAND_TIMEOUT_SECONDS)


@beartype
@ensure(_is_newline_terminated, "must return a newline-terminated lock")
def render_code_review_lock(generated: str, input_bytes: bytes) -> str:
    """Bind an isolated compiled lock to the exact input used to generate it."""
    requirement_body = "\n".join(line for line in generated.splitlines() if not line.startswith("#")).strip()
    if not requirement_body:
        raise ValueError("Code Review compile produced an empty requirements body")
    input_digest = hashlib.sha256(input_bytes).hexdigest()
    return (
        "# This file was autogenerated by "
        "`python scripts/refresh_reproducible_delivery.py --code-review`.\n"
        f"# input-sha256: {input_digest}\n"
        f"{requirement_body}\n"
    )


@beartype
@ensure(lambda result: result is None, "must return None")  # pyright: ignore[reportUnknownArgumentType, reportUnknownLambdaType]
def refresh_code_review_lock() -> None:
    """Atomically regenerate and verify the isolated Code Review lock."""
    validate_locked_export_path(CODE_REVIEW_LOCKED_EXPORT)
    descriptor, temporary_lock_name = tempfile.mkstemp(
        prefix=".code-review-lock-",
        suffix=".txt",
        dir=CODE_REVIEW_LOCKED_EXPORT.parent,
    )
    os.close(descriptor)
    temporary_lock = Path(temporary_lock_name)
    try:
        run(
            [
                "uv",
                "pip",
                "compile",
                str(CODE_REVIEW_REQUIREMENTS_INPUT.relative_to(REPO_ROOT)),
                "--python-version",
                "3.12",
                "--generate-hashes",
                "--no-annotate",
                "--output-file",
                str(temporary_lock.relative_to(REPO_ROOT)),
            ]
        )
        rendered = render_code_review_lock(
            temporary_lock.read_text(encoding="utf-8"),
            CODE_REVIEW_REQUIREMENTS_INPUT.read_bytes(),
        )
        temporary_lock.write_text(rendered, encoding="utf-8")
        os.replace(temporary_lock, CODE_REVIEW_LOCKED_EXPORT)
        run([sys.executable, "scripts/check_reproducible_delivery.py"])
    finally:
        temporary_lock.unlink(missing_ok=True)


@beartype
@ensure(lambda result: result is None, "must return None")  # pyright: ignore[reportUnknownArgumentType, reportUnknownLambdaType]
def _refresh_locked_delivery() -> None:
    """Refresh the primary lock and its hash-protected CI export."""
    validate_locked_export_path(LOCKED_EXPORT)
    descriptor, temporary_export_name = tempfile.mkstemp(
        prefix=".locked-export-",
        suffix=".txt",
        dir=LOCKED_EXPORT.parent,
    )
    os.close(descriptor)
    temporary_export = Path(temporary_export_name)
    try:
        run(["uv", "lock"])
        run(
            [
                "uv",
                "export",
                "--locked",
                "--all-extras",
                "--no-emit-project",
                "--format",
                "requirements-txt",
                "--no-annotate",
                "--output-file",
                str(temporary_export.relative_to(REPO_ROOT)),
            ]
        )
        os.replace(temporary_export, LOCKED_EXPORT)
        run([sys.executable, "scripts/check_reproducible_delivery.py"])
    finally:
        temporary_export.unlink(missing_ok=True)


@beartype
@ensure(lambda result: result in {0, 1}, "must return a shell-compatible status")  # pyright: ignore[reportUnknownArgumentType, reportUnknownLambdaType]
def main(argv: list[str] | None = None) -> int:
    """Regenerate the lock and hash-protected CI export, then verify both."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--code-review",
        action="store_true",
        help="refresh only the isolated Code Review lock and its exact input binding",
    )
    arguments = parser.parse_args(argv)
    try:
        if arguments.code_review:
            refresh_code_review_lock()
        else:
            _refresh_locked_delivery()
    except (OSError, ValueError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        sys.stderr.write(f"frozen delivery refresh failed: {error}\n")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
