#!/usr/bin/env python3
"""Upsert a module entry fragment into a registry index.json file."""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any, cast

import yaml
from beartype import beartype
from icontract import ensure, require


logger = logging.getLogger(__name__)


@beartype
@require(
    lambda index_path: cast(Path, index_path).exists() and cast(Path, index_path).is_file(),
    "index_path must exist and be a file",
)
@ensure(lambda result: isinstance(result, dict), "Returns dict")
def _load_index(index_path: Path) -> dict[str, Any]:
    """Load registry index JSON payload."""
    raw = json.loads(index_path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("Index payload must be a JSON object")
    payload = cast(dict[str, Any], raw)
    modules = payload.get("modules")
    if not isinstance(modules, list):
        raise ValueError("Index payload must include a list at key 'modules'")
    return payload


@beartype
@require(
    lambda entry_fragment: cast(Path, entry_fragment).exists() and cast(Path, entry_fragment).is_file(),
    "entry_fragment must exist",
)
@ensure(lambda result: isinstance(result, dict), "Returns dict")
def _load_entry(entry_fragment: Path) -> dict[str, Any]:
    """Load YAML/JSON entry fragment generated by publish-module.py."""
    raw = yaml.safe_load(entry_fragment.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("Entry fragment must be a mapping object")
    entry = cast(dict[str, Any], raw)
    required_keys = ("id", "latest_version", "download_url", "checksum_sha256")
    missing = [key for key in required_keys if not entry.get(key)]
    if missing:
        raise ValueError(f"Entry fragment missing required keys: {', '.join(missing)}")
    return entry


def _entry_sort_key(item: object) -> str:
    if isinstance(item, dict):
        return str(cast(dict[str, Any], item).get("id", ""))
    return ""


@beartype
def _upsert_entry(index_payload: dict[str, Any], entry: dict[str, Any]) -> bool:
    """Insert or update module entry by id; return True if payload changed."""
    modules_raw = index_payload.get("modules", [])
    if not isinstance(modules_raw, list):
        raise ValueError("Index payload key 'modules' must be a list")
    modules = cast(list[Any], modules_raw)

    entry_id = str(entry["id"])
    for i, existing in enumerate(modules):
        if isinstance(existing, dict) and str(cast(dict[str, Any], existing).get("id", "")) == entry_id:
            if existing == entry:
                return False
            modules[i] = entry
            return True

    modules.append(entry)
    modules.sort(key=_entry_sort_key)
    return True


@beartype
@require(lambda argv: argv is None or isinstance(argv, list), "argv must be a list or None")
@ensure(lambda result: result >= 0, "exit code must be non-negative")
def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Upsert one module entry into registry index.json")
    parser.add_argument("--index-path", type=Path, required=True, help="Path to registry index.json")
    parser.add_argument("--entry-fragment", type=Path, required=True, help="Path to YAML/JSON module entry fragment")
    parser.add_argument("--changed-flag", type=Path, help="Write 'true' or 'false' to this file based on changes")
    args = parser.parse_args(argv)

    try:
        index_payload = _load_index(args.index_path.resolve())
        entry = _load_entry(args.entry_fragment.resolve())
        changed = _upsert_entry(index_payload, entry)
    except (ValueError, json.JSONDecodeError) as exc:
        logger.error("%s", exc)
        return 1

    if changed:
        args.index_path.write_text(json.dumps(index_payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
        logger.info("Updated %s", args.index_path)
    else:
        logger.info("No changes needed in %s", args.index_path)

    if args.changed_flag:
        args.changed_flag.write_text("true\n" if changed else "false\n", encoding="utf-8")

    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    sys.exit(main())
